import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from './components/navbar/Navbar';
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content = (
    <p>Content</p>
  )

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />

        <div className="pt-32">
          {children}
        </div>
        {/* <Modal 
          label='Modal test'
          content={content}
          isOpen={true}
        /> */}
        <LoginModal />
        <SignupModal />
      </body>
    </html>
  );
}
